version: '3'

services:
  app:
    build: .
    ports:
      - "3000:4444" 
    restart : always
    depends_on:
      - db
    environment: 
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: shop
    networks:
      - backend

  db:
    image : mysql:5.7
    ports: 
      - "3307:3307"
    restart : always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes: 
      - container-volume:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - backend

networks: 
  backend:

volumes:
  container-volume:
